return {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    config = function()
        local configs = require("nvim-treesitter.configs")

        configs.setup({
            ensure_installed = {
                "ada",
                "arduino",
                "asm",
                "bash",
                "bibtex",
                "bitbake",
                "c",
                "cmake",
                "comment",
                "cpp",
                "csv",
                "cuda",
                "d",
                "dart",
                "diff",
                "disassembly",
                "dot",
                "doxygen",
                "editorconfig",
                "fortran",
                "gdshader",
                "git_config",
                "git_rebase",
                "gitattributes",
                "gitcommit",
                "gitignore",
                "glsl",
                "gnuplot",
                "go",
                "heex",
                "hlsl",
                "html",
                "http",
                "idl",
                "ini",
                "ipkg",
                "jinja",
                "jq",
                "json",
                "json5",
                "julia",
                "kconfig",
                "latex",
                "linkerscript",
                "llvm",
                "lua",
                "luadoc",
                "make",
                "markdown",
                "matlab",
                "muttrc",
                "nasm",
                "objdump",
                "odin",
                "passwd",
                "perl",
                "printf",
                "proto",
                "python",
                "r",
                "re2c",
                "readline",
                "regex",
                "ruby",
                "slint",
                "sql",
                "ssh_config",
                "strace",
                "sway",
                "systemtap",
                "tcl",
                "tmux",
                "twig",
                "udev",
                "verilog",
                "vhdl",
                "vim",
                "vimdoc",
                "xml",
                "xresources",
                "yaml",
                "zig",
            },
            auto_install = true,
            sync_install = false,
            highlight = { enable = true },
            indent = { enable = true },

            incremental_selection = {
                enable = true,
                keymaps = {
                    init_selection = "<Enter>", -- set to `false` to disable one of the mappings
                    node_incremental = "<Enter>",
                    scope_incremental = false,
                    node_decremental = "<Backspace>",
                },
            },
        })
    end,
}
