return {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    config = function()
        local configs = require("nvim-treesitter.configs")

        configs.setup({
            ensure_installed = {
                "ada",
                "asm",
                "bash",
                "bitbake",
                "c",
                "cpp",
                "csv",
                "cuda",
                "d",
                "devicetree",
                "diff",
                "disassembly",
                "dot",
                "doxygen",
                "dtd",
                "glsl",
                "gnuplot",
                "go",
                "haskell",
                "hlsl",
                "html",
                "idl",
                "ini",
                "java",
                "json",
                "julia",
                "kconfig",
                "latex",
                "linkerscript",
                "llvm",
                "lua",
                "luadoc",
                "make",
                "markdown",
                "markdown_inline",
                "matlab",
                "nasm",
                "objdump",
                "odin",
                "pascal",
                "passwd",
                "perl",
                "proto",
                "python",
                "r",
                "readline",
                "regex",
                "ruby",
                "rust",
                "slint",
                "sql",
                "ssh_config",
                "strace",
                "tcl",
                "tmux",
                "todotxt",
                "toml",
                "udev",
                "verilog",
                "vhdl",
                "vim",
                "vimdoc",
                "xml",
                "yaml",
                "zig",
            },
            auto_install = true,
            sync_install = false,
            highlight = { enable = true },
            indent = { enable = true },

            incremental_selection = {
                enable = true,
                keymaps = {
                    init_Selection = "<Enter>", -- set to 'false' to disable one of the mappings
                    node_incremental = "<Enter>",
                    scope_incremental = false,
                    node_decremental = "<Backspace>",
                },
            },
        })
    end,
}
